drmf_bof
'''Orthogonal Polynomials'''
{{#set:Section=0}}
== Sections in KLS Chapter 1 ==

<div style="-moz-column-count:2; column-count:2;-webkit-column-count:2">
* [[Orthogonal polynomials|Orthogonal polynomials]]
* [[The gamma and beta function|The gamma and beta function]]
* [[The shifted factorial and binomial coefficients|The shifted factorial and binomial coefficients]]
* [[Hypergeometric functions|Hypergeometric functions]]
* [[The binomial theorem and other summation formulas|The binomial theorem and other summation formulas]]
* [[Some integrals|Some integrals]]
* [[Transformation formulas|Transformation formulas]]
* [[The q-shifted factorial|The ''q''-shifted factorial]]
* [[The q-gamma function and q-binomial coefficients|The ''q''-gamma function and ''q''-binomial coefficients]]
* [[Basic hypergeometric functions|Basic hypergeometric functions]]
* [[The q-binomial theorem and other summation formulas|The ''q''-binomial theorem and other summation formulas]]
* [[More integrals|More integrals]]
* [[Transformation formulas|Transformation formulas]]
* [[Some q-analogues of special functions|Some ''q''-analogues of special functions]]
* [[The q-derivative and q-integral|The ''q''-derivative and ''q''-integral]]
* [[Shift operators and Rodrigues-type formulas|Shift operators and Rodrigues-type formulas]]
</div>
== Sections in KLS Chapter 1 ==

<div style="-moz-column-count:2; column-count:2;-webkit-column-count:2">
* [[Orthogonal polynomials|Orthogonal polynomials]]
* [[The gamma and beta function|The gamma and beta function]]
* [[The shifted factorial and binomial coefficients|The shifted factorial and binomial coefficients]]
* [[Hypergeometric functions|Hypergeometric functions]]
* [[The binomial theorem and other summation formulas|The binomial theorem and other summation formulas]]
* [[Some integrals|Some integrals]]
* [[Transformation formulas|Transformation formulas]]
* [[The q-shifted factorial|The ''q''-shifted factorial]]
* [[The q-gamma function and q-binomial coefficients|The ''q''-gamma function and ''q''-binomial coefficients]]
* [[Basic hypergeometric functions|Basic hypergeometric functions]]
* [[The q-binomial theorem and other summation formulas|The ''q''-binomial theorem and other summation formulas]]
* [[More integrals|More integrals]]
* [[Transformation formulas|Transformation formulas]]
* [[Some q-analogues of special functions|Some ''q''-analogues of special functions]]
* [[The q-derivative and q-integral|The ''q''-derivative and ''q''-integral]]
* [[Shift operators and Rodrigues-type formulas|Shift operators and Rodrigues-type formulas]]
</div>
== Sections in KLS Chapter 1 ==

<div style="-moz-column-count:2; column-count:2;-webkit-column-count:2">
* [[Orthogonal polynomials|Orthogonal polynomials]]
* [[The gamma and beta function|The gamma and beta function]]
* [[The shifted factorial and binomial coefficients|The shifted factorial and binomial coefficients]]
* [[Hypergeometric functions|Hypergeometric functions]]
* [[The binomial theorem and other summation formulas|The binomial theorem and other summation formulas]]
* [[Some integrals|Some integrals]]
* [[Transformation formulas|Transformation formulas]]
* [[The q-shifted factorial|The ''q''-shifted factorial]]
* [[The q-gamma function and q-binomial coefficients|The ''q''-gamma function and ''q''-binomial coefficients]]
* [[Basic hypergeometric functions|Basic hypergeometric functions]]
* [[The q-binomial theorem and other summation formulas|The ''q''-binomial theorem and other summation formulas]]
* [[More integrals|More integrals]]
* [[Transformation formulas|Transformation formulas]]
* [[Some q-analogues of special functions|Some ''q''-analogues of special functions]]
* [[The q-derivative and q-integral|The ''q''-derivative and ''q''-integral]]
* [[Shift operators and Rodrigues-type formulas|Shift operators and Rodrigues-type formulas]]
</div>

drmf_eof
