drmf_bof
'''Orthogonal Polynomials'''
{{#set:Section=0}}
== Sections in KLS Chapter 1 ==

<div style="-moz-column-count:2; column-count:2;-webkit-column-count:2">
* [[Orthogonal polynomials|Orthogonal polynomials]]
* [[The gamma and beta function|The gamma and beta function]]
* [[The shifted factorial and binomial coefficients|The shifted factorial and binomial coefficients]]
* [[Hypergeometric functions|Hypergeometric functions]]
* [[The binomial theorem and other summation formulas|The binomial theorem and other summation formulas]]
* [[Some integrals|Some integrals]]
* [[Transformation formulas|Transformation formulas]]
* [[The q-shifted factorial|The ''q''-shifted factorial]]
* [[The q-gamma function and q-binomial coefficients|The ''q''-gamma function and ''q''-binomial coefficients]]
* [[Basic hypergeometric functions|Basic hypergeometric functions]]
* [[The q-binomial theorem and other summation formulas|The ''q''-binomial theorem and other summation formulas]]
* [[More integrals|More integrals]]
* [[Transformation formulas|Transformation formulas]]
* [[Some q-analogues of special functions|Some ''q''-analogues of special functions]]
* [[The q-derivative and q-integral|The ''q''-derivative and ''q''-integral]]
* [[Shift operators and Rodrigues-type formulas|Shift operators and Rodrigues-type formulas]]
</div>
== Sections in KLS Chapter 9 ==

<div style="-moz-column-count:2; column-count:2;-webkit-column-count:2">
* [[Wilson|Wilson]]
* [[Racah|Racah]]
* [[Continuous dual Hahn|Continuous dual Hahn]]
* [[Continuous Hahn|Continuous Hahn]]
* [[Hahn|Hahn]]
* [[Dual Hahn|Dual Hahn]]
* [[Meixner-Pollaczek|Meixner-Pollaczek]]
* [[Jacobi|Jacobi]]
* [[Jacobi: Special cases|Jacobi: Special cases]]
* [[Pseudo Jacobi|Pseudo Jacobi]]
* [[Meixner|Meixner]]
* [[Krawtchouk|Krawtchouk]]
* [[Laguerre|Laguerre]]
* [[Bessel|Bessel]]
* [[Charlier|Charlier]]
* [[Hermite|Hermite]]
</div>
== Sections in KLS Chapter 14 ==

<div style="-moz-column-count:2; column-count:2;-webkit-column-count:2">
* [[Askey-Wilson|Askey-Wilson]]
* [[q-Racah|''q''-Racah]]
* [[Continuous dual q-Hahn|Continuous dual ''q''-Hahn]]
* [[Continuous q-Hahn|Continuous ''q''-Hahn]]
* [[Big q-Jacobi|Big ''q''-Jacobi]]
* [[Big q-Jacobi: Special case|Big ''q''-Jacobi: Special case]]
* [[q-Hahn|''q''-Hahn]]
* [[Dual q-Hahn|Dual ''q''-Hahn]]
* [[Al-Salam-Chihara|Al-Salam-Chihara]]
* [[q-Meixner-Pollaczek|''q''-Meixner-Pollaczek]]
* [[Continuous q-Jacobi|Continuous ''q''-Jacobi]]
* [[Continuous q-Jacobi: Special cases|Continuous ''q''-Jacobi: Special cases]]
* [[Big q-Laguerre|Big ''q''-Laguerre]]
* [[Little q-Jacobi|Little ''q''-Jacobi]]
* [[Little q-Jacobi: Special case|Little ''q''-Jacobi: Special case]]
* [[q-Meixner|''q''-Meixner]]
* [[Quantum q-Krawtchouk|Quantum ''q''-Krawtchouk]]
* [[q-Krawtchouk|''q''-Krawtchouk]]
* [[Affine q-Krawtchouk|Affine ''q''-Krawtchouk]]
* [[Dual q-Krawtchouk|Dual ''q''-Krawtchouk]]
* [[Continuous big q-Hermite|Continuous big ''q''-Hermite]]
* [[Continuous q-Laguerre|Continuous ''q''-Laguerre]]
* [[Little q-Laguerre / Wall|Little ''q''-Laguerre / Wall]]
* [[q-Laguerre|''q''-Laguerre]]
* [[q-Bessel|''q''-Bessel]]
* [[q-Charlier|''q''-Charlier]]
* [[Al-Salam-Carlitz I|Al-Salam-Carlitz I]]
* [[Al-Salam-Carlitz II|Al-Salam-Carlitz II]]
* [[Continuous q-Hermite|Continuous ''q''-Hermite]]
* [[Stieltjes-Wigert|Stieltjes-Wigert]]
* [[Discrete q-Hermite I|Discrete ''q''-Hermite I]]
* [[Discrete q-Hermite II|Discrete ''q''-Hermite II]]
</div>

drmf_eof
